### ISSUE TITLE
არ აჯობებს ჩოისფილდი ინტეჯერი იყოს (შეგიძლია enum კლასი გამოიყენო)

### ISSUE THREAD

**Issue by MariamKipshidze** [SabaXdev/django-final-project-lms#1]
https://github.com/SabaXdev/django-final-project-lms/blob/da7dd6da73481c03442ee20d85e67d529dda07e6/users/choices.py#L1

**Comment by SabaXdev** [comment]
მირჩევნია ასე დავტოვო

**Comment by MariamKipshidze** [comment]
@SabaXdev რატომ?

**Comment by SabaXdev** [comment]
Choisefield - ის შემთხვევაში choise -ები ს ფილტრაცია და ამოღება უფრო მარტივია , მაშინ როდესაც enum ითხოვს დამატებით mapping-ს value- ებსა და field-ებს შორის.
